services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: rakshith0908/learnify-p-user-service:latest
    environment:
      - MYSQL_DB=authentication
      - MYSQL_HOST=mysql_db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - HASH_SECRET=43B179787E782F88F48326BC4C249
      - JWT_SECRET=88kAMDtEFozukL7INMMq4pHSC33gybuXu7MzpHMkEu3NbItS3kLFAoDgC8qX4y8M
    depends_on:
      mysql_db:
        condition: service_healthy
  course-service:
    build:
      context: ./course-service
      dockerfile: Dockerfile
    image: rakshith0908/learnify-p-course-service:latest
    environment:
      - MONGO_USERNAME=root
      - MONGO_PW=root
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=course-service
    depends_on:
      mongodb:
        condition: service_healthy
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    image: rakshith0908/learnify-p-notification-service:latest
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "my-topic:1:1"
    volumes:
      - kafka_data:/var/lib/kafka
    depends_on:
      - zookeeper
  mysql_db:
    image: mysql:8.0
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=authentication
    volumes:
      - mysql_data:/var/lib/mysql
  mongodb:
    image: mongo:latest
    ports:
      - "27000:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo_data:/data/db
volumes:
  mysql_data:
  mongo_data:
  kafka_data:
