apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configmap
data:
  KAFKA_ADVERTISED_PORT: "9092"
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://akafka:9092
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181