apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  labels:
    app: course-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: rakshith0908/learnify-p-course-service:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: course-service-configmap
            - secretRef:
                name: course-service-secret
